### ISSUE TITLE
Search doesn't return all expected benches

### ISSUE THREAD

**Issue by arizonagroovejet** [openbenches/openbenches.org#122]
As a user I would expect https://openbenches.org/bench/2251 to be included in these search results
https://openbenches.org/search/?search=happy+memories
but it isn't. The bench is included in these search results
https://openbenches.org/search/?search=broadbent
so the search can "see" that bench.

I suspect the reason for this behaviour is this line
https://github.com/edent/openbenches/blob/724242d384c4717a712abbad1e20f146c6900581/www/mysql.php#L645

**Comment by edent** [comment]
Yup. Was originally hard coded for 10 results because I didn't want to implement pagination.

Please go ahead and make a PR to change the search limit.

**Comment by arizonagroovejet** [comment]
Any thoughts on what would be a good value to change it to? 

I think the answer should maybe be influenced by: 
- There's no minimum number of characters required to do a search and it'll also accept  "%". (Maybe a minimum number of characters should be enforced and "%" rejected?)
- Results are a bit huge dense block of text. (I think I have a very easy improvement could be made there, sticking  `margin: 1em 0` on li elements).

Maybe those things should be raised as issues and marked as blockers to this.

**Comment by edent** [comment]
I trust you.

**Comment by arizonagroovejet** [comment]
I believe this issue has been solved by ba8dca171e8a2840b8e1852e99fd639b0d6351b7
