### ISSUE TITLE
Uploads from iPhone broken

### ISSUE THREAD

**Issue by ajhard** [openbenches/openbenches.org#131]
You’re probably aware but there seems to be some issues when uploading pictures from iPhone (however not on iPad).  When I create a new bench, and use the file picker to attach three pictures (all taken with the iPhone & GPS enabled) the bench is created successfully and the first pic is uploaded, however the other 2 fail with an error related to lack of GPS data.  If I create the same bench using my iPad and the exact same pictures - using drag & drop between the photos app and Safari then all works as expected.  It would be great to fix this as currently it means I can’t create benches on the iPhone.  This issue was present on my old 7 and also on my new X.

**Comment by edent** [comment]
Thanks. I don't have an iPhone to test on, but I'll try to get to the bottom of it.

**Comment by ajhard** [comment]
So I just did a test, I selected 3 photos, and the 1st uploaded ok, the edit screen comes up with just the one showing, if I then add the other 2 again, I get the attached error saying no GPS, and the second error message when I submit the edit.

![aa92386b-6dc8-4a32-8551-504d7df9680a](https://user-images.githubusercontent.com/30599787/33346551-0b97c9c0-d488-11e7-956b-4eabeba66dde.png)
![78ca4793-13de-4685-86c6-763dd547e6ec](https://user-images.githubusercontent.com/30599787/33346552-0bd959a8-d488-11e7-8ea6-fa81b93032b1.png)

**Comment by edent** [comment]
I've reported this bug to Apple, as it appears to be a Safari problem. Will see if there's any way around it.

> It's a shame (but understandable) that Mobile Safari on iOS 11 doesn't seem to allow access to GPS data from uploaded photos - I had to export from Photos app on OS X instead

https://twitter.com/simonw/status/946309525115670528

Grrr!

**Comment by edent** [comment]
Reported to apple. Apparently fixed on the latest iPhone X.
![screenshot_20180104-201100__01](https://user-images.githubusercontent.com/837136/34680819-fce73a80-f491-11e7-8b34-a8a7aeae6fe1.jpg)

**Comment by edent** [comment]
Is this still a problem? I don't have an iPhone to test with.

**Comment by ajhard** [comment]
Haha - it is, and this is amazing timing, I was sitting on the beach yesterday trying a few things out.  Basically on the iPhone if I use the safari ‘Photo Library’ option to upload direct from the browser it fails to pass any GPS data and the creation fails.  If I first share the photos from the Photos app to the Files app and then use the ‘Browse’ option in Safari it works perfectly.  From the iPad if I drag & drop from Photos to Safari it also works.  It’s not ideal as it means if I am out with just the phone I need to jump through the hoop of sharing the images twice...

**Comment by edent** [comment]
Can you take a photo straight from the select photo menu?

I'm going to have to see if there's a better way to do this.

**Comment by ajhard** [comment]
You can - but that also fails with the same no GPS error.

**Comment by edent** [comment]
Gah!

**Comment by ajhard** [comment]
It is weird - and I don’t think it can be a widespread iOS issue with photo uploads missing GPS because there are loads of threads telling you how to upload without sending GPS and none discussing this problem!

**Comment by ukmoose** [comment]
I happily take photos on my iphone and upload direct to the site (using the standard camera app to take and then select photo option on upload)

**Comment by edent** [comment]
This is *so* frustrating! It works for some people and not for others.
@ukmoose which iPhone model & software do you have?  Would you mind writing a quick step-by-step? Have you changed any privacy settings?

**Comment by ajhard** [comment]
I don’t think it can be related to a specific model or software version as I have had this issue for a good long while and have been through many iPhones in that time!!  Definitely a 7 and an X and running iOS 11 and 12 beta, probably 10 also.

One thing that does occur to me is that I have always used iCloud Photo Library - @ukmoose do you use that or are the photos only stored locally for you?  I’m inclined to log a ticket with apple and see if they have any ideas.

**Comment by ajhard** [comment]
Very strange, but it seems to be working today...for no apparent reason!
Only change on my end is that I am now on iOS 12 Dev Beta 12.
Took some pics yesterday and they have uploaded just fine from the iPhone, so fingers crossed it stays that way...

**Comment by ajhard** [comment]
I think I have found the solution - and understand why other users like @ukmoose aren’t having the same problem.  From iOS 11 onwards iPhone 7 and above started using HEIF as standard instead of JPEG and they convert on the fly when needed.  I think this drops EXIF data, and the reason it works sometimes is that the device may decide to shoot in JPEG.  There’s an option in camera settings to always use JPEG instead (for compatibility) I’ve switched this on and will see but initial experience looks good!  Fingers crossed & a shame Apple support didn’t know this...

**Comment by ukmoose** [comment]
Alternatively shoot with "live" on and then for the first photo to be uploaded for a bench, edit the photo in photos to turn "live" off

**Comment by edent** [comment]
I've added instructions for iPhone users at https://www.openbenches.org/blog/2023/05/iphone-instructions/

I'll link to them from the upload page.
