### ISSUE TITLE
Leaderboard not picking up all benches

### ISSUE THREAD

**Issue by ukmoose** [openbenches/openbenches.org#132]
Not that I'm competitive...

But I noticed that the leaderboard isn't picking up all the submissions.
So for example https://openbenches.org/user/twitter/ukmoose 

doesn't include 
https://openbenches.org/bench/3083/
or
https://openbenches.org/bench/2767/

**Comment by edent** [comment]
I think that is because someone else has edited them (either logged in or anonymously). So they get to "claim" it. An imperfect system, to be sure!

Will check at the weekend.

**Comment by edent** [comment]
Hmm - and some people are listed on the Leaderboard as having uploaded benches, but don't appear to have any.... https://openbenches.org/user/4620/

**Comment by edent** [comment]
The leaderboard now only looks at uploads and photos. Edits don't count towards you points.

Please remember that Internet points cannot be redeemed for fabulous prizes.
