### ISSUE TITLE
Using BirdgyFed to connect OpenBenches.org to the IndieWeb and the fediverse

### ISSUE THREAD

**Issue by strypey** [openbenches/openbenches.org#156]
I came here after reading about your experience being [bot-spanked by the birdsite](http://www.openbenches.org/blog/2018/05/twitter-suspended-our-account-and-wiped-all-our-followers/), where you said:

> Yes, I know. We should redecentralize and put our content on Mastodon, or the BlockChain, or some other convoluted platform which has no users.

The response I started writing here got long, so I posted it on my blog instead:
https://www.coactivate.org/projects/disintermedia/blog/2018/05/08/use-both-a-response-to-openbenches-comments-about-decentralizing-the-social-web/

The key pieces of info I wanted to share are:
* Mastodon is part of a larger network known informally as [the fediverse](https://medium.com/we-distribute/a-quick-guide-to-the-free-network-c069309f334), all inter-operating via OStatus.
* If you don't want to set up a separate microblog app on your own server, you can use [IndieWeb protocols](https://indieweb.org/friendly) to enable your existing openbenches.org website to inter-operate as a first-class citizen of the social web, both with the rest of the IndieWeb, and eventually with the rest of the fediverse using [BridgyFeb](https://fed.brid.gy/#work) (note: BridgyFed is about a year old and still experimental).
* W3C recently made [ActivityPub](http://activitypub.rocks/) an official web standard for social networking, and all the fediverse apps either have implementation rolled out (eg Mastodon), or are working on it, and the same is true for a [growing list of other apps](https://gitlab.com/fediverse/fediverse.gitlab.io/issues/8), (including BridgyFeb).

Someone once convinced you to use the birdsite because they were already there. You could be that person/ project in the fediverse for your social network.

**Comment by edent** [comment]
Thanks.  A few points.

I'm already on mastodon, usually as @edent :-)

OpenBenches has lots of semantic data on the website, including schema.org stuff - there's also an open data feed on there.

All the Twitter functionality is a) posting a duplicate to Twitter, b) Login.

If you can write a Pull Request to add Mastodon / Fediverse functionality - I'll gladly accept it.

**Comment by strypey** [comment]
On 2018-05-08 13:11, Terence Eden wrote:
> If you can write a Pull Request to add Mastodon / Fediverse
> functionality - I'll gladly accept it.

Sadly I don't have the skills to do this, I'm just an opinionated user
(who likes memorial benches ;) But I can ask around. What language(s),
framework(s), libraries does your site use? Knowing this might narrow
down a shortlist of people to shouldertap.

**Comment by edent** [comment]
As an update, we're on Mastodon at https://botsin.space/@openbenches

That just uses IFTTT to push new items from the RSS feed onto the Fediverse.  There is oEmbed on each URl, so it should have a rich preview. 

Posting our media to botsin.space seems to be discouraged - which is understandable as there is a lot of it.

I'd be open to someone working out how I can turn an RSS feed into an ActivityPub stream for others to consume.

**Comment by strypey** [comment]
@edent
> we're on Mastodon

Awesome, followed :)

> how I can turn an RSS feed into an ActivityPub stream

This might be useful:
https://git.hostux.net/valere/rss-to-activitypub

**Comment by edent** [comment]
We're now autoposting to Mastodon. If there's an *easy* to use ActivityPub library for PHP, I'll take a look at making us a full-time part of the Fediverse.
