### ISSUE TITLE
Text detection seems broken.

### ISSUE THREAD

**Issue by arizonagroovejet** [openbenches/openbenches.org#199]
Selecting an image for Geotagged Photo consistently results in the message:

> Automatic text detection encountered an error: error Bad Request. Sorry about that. Please enter the inscription yourself.

Looking in Firefox console I see
```
Request URL:https://vision.googleapis.com/v1/images:annotate?key=undefined
Request method:POST
Remote address:216.58.210.42:443
Status code: 400
``` 
Shouldn't the `key` value be something other than `undefined`?

**Comment by edent** [comment]
Thanks for letting me know.
