### ISSUE TITLE
Be able to keep being shown random benches.

### ISSUE THREAD

**Issue by arizonagroovejet** [openbenches/openbenches.org#200]
As a user, I would like to be able to access a never ending series of randomly selected benches.

After clicking "Random bench" on the front page there is no way to get another random bench without going back to the front page.

I don't know where a "Random bench" would be best placed on the bench pages. I was thinking perhaps next to the "Share bench" button, but there is perhaps a technical consideration in that the "Random bench" button on the front page works by being in a `<form>` which is a block level element, where as the purple buttons on a bench page are `<a>` elements.

**Comment by edent** [comment]
Agreed. We should also keep the search bar there as well.
