### ISSUE TITLE
Content on bench pages jumps during loading.

### ISSUE THREAD

**Issue by arizonagroovejet** [openbenches/openbenches.org#201]
There's no height specified for images on bench pages. Even on a connection with ~70MB/s down when I view a bench page I often see content jumping. E.g. the page looks like this for a couple seconds:
![Screenshot from 2019-07-08 20-56-43](https://user-images.githubusercontent.com/29510692/60838662-243a3580-a1c3-11e9-85a8-1cffe5b927c7.png)
Then all the content shifts down once the images load, which is kind of ugly. 

The aspect ratio of photos varies (e.g. some photos are portrait rather than landscape) so specifying a single height for all images wouldn't produce good results. I tinkered with this a while back and came up with something that worked out the height of an image by getting the dimensions of the original, then doing something like `$h=(600/original_width)*original_height` and putting `height="$h"` in the HTML. I can't find the code and the code around serving images has changed since.

**Comment by edent** [comment]
Yup. There is now some image size code. So this should be incorporated.

**Comment by edent** [comment]
https://github.com/openbenches/openbenches.org/blob/master/www/functions.php#L502

**Comment by edent** [comment]
Causes some issues on small screens due to max width being set

![Screenshot_20190712-095140](https://user-images.githubusercontent.com/837136/61115635-ca6b9100-a48a-11e9-9eb2-6cd3b5b5f80c.jpg)

**Comment by edent** [comment]
It turns out the answer is "no".  When the viewport is narrow, this causes problems.

If the height is set - the width will be too wide.

So set the max-width? Nope - that changes the aspect ratio.

I'm going to set the compression to be slightly lower - 75% on JPG and WEBP - but I think the real delay is the CDN loading the images from our site.

**Comment by edent** [comment]
Closing for now as we've moved to a much faster CDN. Let me know if it is still a problem.
