### ISSUE TITLE
database export missing tables `tags` and `tag_map`

### ISSUE THREAD

**Issue by mflint** [openbenches/openbenches.org#202]
# Description

The file `database/database_export.sql` is missing two tables:
* tag
* tag_map

# Impact

This leads to failures if we rely on `database/database_export.sql` to create a correct database schema.

# Workaround

We can run _both_ `database_export.sql` and `database structure.sql` scripts, and ignore any errors, but I don't think this was the intention.

Should I expect that `database_export.sql` contains the table definitions and data for _all_ tables, or should the `structure` script have the table definitions, leaving the `export` script to do only the data inserts?

**Comment by edent** [comment]
Yup, that's a bug on my part. I'm on holiday at the moment, so will fix it at the end of September.

**Comment by mflint** [comment]
No worries @edent - enjoy the holiday! 🏖
