### ISSUE TITLE
Schema only supports one inscription per bench

### ISSUE THREAD

**Issue by mflint** [openbenches/openbenches.org#206]
# Description

Benches often have multiple plaques/inscriptions, but the database schema only supports one inscription per bench.

# Impact

* anyone submitting a multi-plaque bench must enter the second (and third…) inscription manually
* automatic text recognition _could_ concatenate multiple OCR results into one value, but it would be better to record each inscription separately in the database
* the single `inscription` column for a multi-plaque bench currently contains the inscriptions from all the plaques, which may lead to more search results than the user was expecting

# Proposed solution

This would need a database migration, so it’s not an easy feature to implement - and would certainly need multiple pull requests.

I think it could be done with no downtime, if the deployment is broken down into these steps:

## Step 1: Create `inscription` table

| column            | type                  | description                  |
| ----------------- | --------------------- | ---------------------------- |
| `inscriptionID`   | `bigint(20) NOT NULL` | primary key                  |
| `benchID`         | `bigint(20) NOT NULL` | foreign key to `bench` table |
| `inscriptionText` | `text NOT NULL`       | inscription                  |

## Step 2: Create `inscription_history` table

| column            | type                  | description                  |
| ----------------- | --------------------- | ---------------------------- |
| `inscriptionID`   | `bigint(20) NOT NULL` | primary key                  |
| `benchID`         | `bigint(20) NOT NULL` | foreign key to `bench` table |
| `inscriptionText` | `text NOT NULL`       | inscription                  |
| `changed`         | `datetime NOT NULL`   | change time                  |

## Step 3: Create trigger `save_inscriptions_history` to update `inscription_history`

This would be similar to existing `save_benches_history` trigger.

## Step 4: Create trigger on `bench` insert, to create a new row in `inscription`

This would create a new `inscription` row whenever a new `bench` is inserted, if the inscription text is non-null.

## Step 5: Create trigger on `bench` update, to update row in `inscription`

This would update an existing row in `inscription` whenever a `bench` row is updated (if the `inscription` row exists and the inscription text is non-null).

When step 5 is complete, then any new or changed inscriptions would be mirrored to the new `inscription` table.

## Step 6: Run script to create `inscription` rows for each existing row in `bench` table

This would create a new row in `inscription` table for every existing `bench`.

When this step is complete, `bench.inscription` and `inscription.inscriptionText` columns would always be in sync.

## Step 7: Change all php code which reads legacy `inscription` column in `bench` table, to use the new `inscription` table

This affects any code which performs a `SELECT ... FROM bench` query, to perform a join between `bench` and `inscription`, taking the inscription text from `inscription` instead of `bench`.

Some queries would be OK to return multiple records in the resultset; other queries may need a new `LIMIT 1` clause.

Affected files:
* mysql.php
* sitemap.xml.php

When this step is complete, inscriptions are always written to the `bench` table but read from `inscription`.

## Step 8: Alter table `bench` to make `inscription` column nullable

Nothing is reading the `bench.inscription` column now, so we can make it nullable, in preparation for changing the code which updates/inserts to the `bench` table.

## Step 9: Change all php code which inserts/updates inscriptions to use the new `inscription` table instead

This would now:

* insert a new row to `inscription` table, instead of inserting a value into the `bench.inscription` column
* update an existing row in `inscription` table, instead of updating the `bench.inscription` column

When this step is complete, the legacy `bench.inscription` column will not be used by any php code.

## Step 10: Delete two triggers which copy data from `bench` table to `inscription`

These are now not needed, and must be dropped before the `bench.inscription` column is removed.

## Step 11: Alter table `bench` to drop column `inscription`

Nothing is using the legacy `inscription` column now, so it may be dropped.

## Step 12: Change `add.php` to enable inscriptions for multiple images

Add textfield to the "add bench" webpage, so users can enter more than one inscription. (When the image media-type is `inscription`).

## Step 13: Change `add.php` to enable OCR for multiple images

When the image media-type is `inscription`.

# Limitations after implementing this feature

Search results might start returning the same bench twice. (Probably OK, because "bench search" is really an "inscription search")

Some parts of the application would still just display a single inscription:

* map-feature inscription popups
* twitter messages
* rss feed

# Questions

* do we want an `added` datetime column in the `inscription` table? I don't see any reason not to.
* should `inscription` table have a foreign-key link back to the `media` table? This might be useful, but the migration step may need to make some ugly assumptions
* would `inscription` table need some kind of order column, so that any function which requires just one inscription would consistently get the same one each itme? Would also require adding an `ORDER BY` clause to some SQL queries.
* would we need a final (manual) tidy-up phase, to fix existing benches whose `inscription` value contains text from multiple plaques?

**Comment by edent** [comment]
Thank you for all the effort you've put in to this. I think we need to start at the other end.

What does this look like for the user when adding a bench?

**Comment by arizonagroovejet** [comment]
This seems like it's based on an unstated and false assumption that a bench having multiple plaques means there are multiple photos of plaques that need to be uploaded.

>   anyone submitting a multi-plaque bench must enter the second (and third…) inscription manually

Not true. Often plaques are close enough to be, and are, captured in the same photo and still be easily readable. (E.g. https://openbenches.org/bench/1108 https://openbenches.org/bench/11908) Photos of multiple plaques could be stuck together in to one image and uploaded (E.g. https://openbenches.org/bench/8616) 

> automatic text recognition could concatenate multiple OCR results into one value, but it would be better to record each inscription separately in the database

Why would it be better? In cases where multiple plaques are close enough to be in a single photo how would the text from each plaque get recorded separately?

>   the single inscription column for a multi-plaque bench currently contains the inscriptions from all the plaques, which may lead to more search results than the user was expecting

Some examples of this would be interesting. The only circumstance I can think of where it might happen is if the search term is `foo bar` and one inscription ends with `foo` with no punctuation or anything after it and the inscription after it starts with `bar`. E.g. https://openbenches.org/bench/13262 appears in search results for `1973 PRESENTED`. https://openbenches.org/search/?search=1973+PRESENTED  This seems very unlikely to happen in real usage and not really a problem if it does.

Reading this issue makes me realise I think it might be possible to improve the user experience for someone uploading a bench for which they have more than photo containing a plaque. I have some ideas on how that might be done but not sure this issue is place to describe them since they're about changes to changes to user interface and experience, not to database schema.

**Comment by mflint** [comment]
> What does this look like for the user when adding a bench?

* user takes photographs of two plaques
* selects first plaque photo
* selects "this file is a close-up of the inscription"
* automatic text detection happens
* user selects second plaque photo
* selects "this file is a close-up of the inscription" for second photo
* another textfield appears
* automatic text detection happens
* user selects photo of bench
* selects "this file is a long shot of the bench" for third photo
* user saves bench

So the screen would show these elements:
* Choose File (first photo)
* Preview of first photo
* Photo type selection (first photo)
* Textfield (first photo, because this is a "close-up of the inscription)
* Choose File (second photo)
* Preview of second photo
* Photo type selection (second photo)
* Textfield (second photo, because this is another "close-up of the inscription)
* Choose File (third photo)
* Preview of the third photo
* Photo type selection (third photo)
* Choose tags
* Map
* "Share Bench" button

(So an inscription textfield appears wherever the user has selected "inscription close-up")

@arizonagroovejet wrote:
> This seems like it's based on an unstated and false assumption that a bench having multiple plaques means there are multiple photos of plaques that need to be uploaded.

I'd disagree that this is a false assumption. I've submitted benches where separate inscriptions would be useful.

You cite some examples:

https://openbenches.org/bench/11908: Yes, these plaques are close together, but the automatic text recognition isn't going to work well here, for all three plaques. The text for all three gets mixed up.

https://openbenches.org/bench/8616: Clever - but beyond the capabilities of most people uploading photos. And again, automatic text recognition won't work well.

> Why would [separate inscriptions] be better?

Because somebody uploading photos might expect that automatic text recognition works for multiple separate plaque photos. In [this example](https://openbenches.org/bench/12828), I had two choices:
1. take one photograph of _both_ plaques, accepting that text recognition will fail, and I'll need to fix the text of both inscriptions
2. take two photographs, one of each bench. Text recognition will work for the first, but not the second. I'll need to type the second inscription

In both cases, the database stores _both_ inscriptions in a single value; it has no knowledge of these being two separate inscriptions, other than the `multiple plaques` tag. It certainly can't tell where one inscription ends and the next one begins. Is the text "x xxx xxx" at the bottom of the first plaque, or the top of the second?

> Reading this issue makes me realise I think it might be possible to improve the user experience for someone uploading a bench for which they have more than photo containing a plaque.

Absolutely, yes - regardless of any database changes. But without database changes, the best we can do is concatenate multiple inscriptions into one piece of text.

Thank-you @arizonagroovejet for sharing your thoughts 👍

**Comment by arizonagroovejet** [comment]
> * user takes photographs of two plaques

What if they don't take photograph**s** of the two plaques? If they've taken a single photo that contains multiple plaques, how does the text from each plaque end up in separate database fields? If it doesn't we'll end up with a situation where for some benches with multiple plaques all the text is in a single field and for some it's split between multiple fields. Someone would have put a lot of work in to creating inconsistency and that doesn't seem desirable.

 > This seems like it's based on an unstated and false assumption that a bench having multiple plaques means there are multiple photos of plaques that need to be uploaded.
 >>  I'd disagree that this is a false assumption. I've submitted benches where separate inscriptions would be useful.

I'm afraid I'm not seeing how that explains how you are not making the assumption. Your description of what text from each plaque getting stored in separate database fields looks like for the user when adding a bench starts with the user taking separate photos of each plaque, which really re-enforces my thinking that you are making that assumption.

>  Why would [separate inscriptions] be better?
>> Because somebody uploading photos might expect that automatic text recognition works for multiple separate plaque photos. 

That is an entirely reasonable expectation for someone to have and it would be good for it to be met. But it's not a reason why storing text from each plaque in a separate database field would be better. Text recognition working on multiple plaque photos and the text from each plaque being stored in a separate database field are two separate things. The former can be achieved without the latter. As you said yourself, the user experience can be improved "regardless of any database changes".

What if a bench has multiple plaques and the text on them is not self contained? A totally made up example would be a plaque which says `The quick brown fox`  then next to it is a plaque which says  `jumps over the lazy dog`. (Maybe for some reason it's only possible to attach very small plaques to this bench. :) ) If someone searches for `fox jumps` and the text from each plaque is in separate database fields, that bench isn't going to appear in search results and really it should.

> But without database changes, the best we can do is concatenate multiple inscriptions into one piece of text.

Which is of course what is effectively currently happening. And what I'm still not getting is, given that the user experience of uploading benches with multiple plaques can be improved without making any database changes, what are the practical benefits to users of the text from each plaque being stored in a separate database field? What problems exist for users that would be solved by doing it? What would it be possible for users to do with the data that isn't currently possible? Would achieving those things be worth all the work? Are those things more desirable that not creating the limitations you listed? Unless I've missed something the only example of a benefit so far is it solves this:

> which may lead to more search results than the user was expecting

which I'm sure sure is even really a problem. I've thought of one case in which that might occur and no others have been suggested.

**Comment by edent** [comment]
I *like* the idea of having a bench table, and a separate inscription table.  It would make it easier for multiple plaques, and saving metadata about the language of the inscription etc.

But - I want to know how big a problem this is, and what the user solution looks like before committing to anything.

So, if someone can work out how many benches in the DB have multiple plaques, that'd be a start (if it's less than 1%, I'm not sure it's worth making a change, for example).

Secondly, I think the user upload experience probably needs an overhaul first. It's still a bit ropey and prone to error. Once that's better, we can sketch out how a multi-upload + instructions could look.

Later today I'll be making a DB change to put more image metadata in the DB. Should speed things up!

**Comment by mflint** [comment]
Wow, I’m surprised by the response there, having thought this would be an uncontroversial suggestion. 

Just trying to help, but honestly I can’t be arsed arguing.

**Comment by edent** [comment]
I do like the idea. I just want to know how big an issue it is before doing the work. If you're happy to help build the UI, I'm totally happy to go with it.

**Comment by arizonagroovejet** [comment]
I like the idea of text from each plaque being in a separate database field, in theory. There is a nice logic and neatness to it. But I see problems with it, a lack of practical benefit, feel like it's being presented as the way to improve something that is independent of what the database schema is. I  expressed those things very much aiming for discussion rather than argument. Perhaps I need to work on my aim.
