### ISSUE TITLE
Map doesn't display on front page or for specified locations

### ISSUE THREAD

**Issue by arizonagroovejet** [openbenches/openbenches.org#212]
https://openbenches.org/ is displaying the 404 page instead of the map.

Going to a page for a specific page, then clicking "Benches near this",  E.g. https://openbenches.org/#53.960972/-1.086261/16 also displays 404 instead of the map.

I suspect the addition at line 146 in https://github.com/openbenches/openbenches.org/commit/03f135c6482eff81ab78ff2fbe6ec8843e6f438f#diff-df61020b75a730cc7203a9e2aae58e72R146

**Comment by edent** [comment]
You didn't see nuffink, right!
