### ISSUE TITLE
Location icon prevents other pins being clicked

### ISSUE THREAD

**Issue by danielthepope** [openbenches/openbenches.org#224]
When browsing the map with your location turned on, some of the items on the map are unable to be clicked. See this example:
![image](https://user-images.githubusercontent.com/5173183/76690154-4d09a900-6635-11ea-9a72-6e806a8ad8ed.png)
Of the two pins inside this circle, the lower one can be clicked, but the one above cannot. Also the number 5 in the circle can't be clicked either.
I think this is due to how icons are drawn on the map. Would it be possible to put the location circle on a different layer? Do layers even exist?

**Comment by edent** [comment]
Do layers exist? Do *we* even exist, man?

I can reproduce this - so will look at fixing it shortly.

**Comment by danielthepope** [comment]
OK, I wonder if https://github.com/openbenches/openbenches.org/blob/master/www/front.php#L86 should be an `imageOverlay` instead of a `marker`?
https://leafletjs.com/reference-1.6.0.html#imageoverlay looks appropriate

**Comment by edent** [comment]
Kept it as an icon but set the z-index to be at the bottom of the stack.

**Comment by danielthepope** [comment]
Works great now, thanks!
