### ISSUE TITLE
There are people who don't bother to check if a bench has already been submitted.

### ISSUE THREAD

**Issue by arizonagroovejet** [openbenches/openbenches.org#225]
As a stop gap measure to #5 maybe some words could be added to https://openbenches.org/add/ like "Before adding a bench, please take a minute to check whether it has already been submitted." Maybe mention that people can add new photos to a previously submitted bench.

**Comment by edent** [comment]
I have personally asked a specific user to check that benches exist before adding. That hasn't made a difference to their behaviour. I'm not sure if a bit of text will stop them.

Given that *most* benches aren't duplicates, I think I'd rather keep instructions to a minimum. But this is a good reminder that I need to build a proper "merge" interface. And work on duplicate detection.

**Comment by arizonagroovejet** [comment]
People are strange. Duplication detection seems difficult for reasons mentioned in #5 but I suppose it's probably easier than "fixing" people. :D
