### ISSUE TITLE
Merge benches

### ISSUE THREAD

**Issue by JonTheNiceGuy** [openbenches/openbenches.org#227]
https://twitter.com/jontheniceguy/status/1300689185460957187

I uploaded a bench that I later found already existed. Is there some way to "Merge benches" - i.e. take the photos from bench A and bench B, put them both on bench A and then create a pointer from bench B to bench A?

Some checks that might be worth putting in place...

* Text is "similar" (e.g. perhaps 90% of the characters, excluding whitespace, match?)
* Geolocation is close (e.g. perhaps Lat and Long should have a +/-0.0005 variance?)

Perhaps optionally offer the chance to replace the text on bench A with bench B?

**Comment by JonTheNiceGuy** [comment]
More examples: 

* https://openbenches.org/bench/4025 and https://openbenches.org/bench/16709
* https://openbenches.org/bench/4027 and https://openbenches.org/bench/16685
* https://openbenches.org/bench/4026 and https://openbenches.org/bench/16684
* https://openbenches.org/bench/4068 and https://openbenches.org/bench/16687
* https://openbenches.org/bench/4069 and https://openbenches.org/bench/16689
* https://openbenches.org/bench/4070 and https://openbenches.org/bench/16691
* https://openbenches.org/bench/4066 and https://openbenches.org/bench/16703
* https://openbenches.org/bench/4064 and https://openbenches.org/bench/16702
* https://openbenches.org/bench/4063 and https://openbenches.org/bench/16701
* https://openbenches.org/bench/4061 and https://openbenches.org/bench/16699
* https://openbenches.org/bench/4062 and https://openbenches.org/bench/16700

Looking for more, but work keeps getting in the way :wink:

**Comment by edent** [comment]
Thanks for all of these! We do have a super-secret merge function which is accessible to administrators. I'll merge those now.

As you've identified, part of the problem is that location can be out by tens of metres, and the OCR isn't always accurate.

I think asking people if they want to merge would be a barrier and a bit confusing. It would be better to create a search which shows an admin a list of possible merge candidates.

The DB is on GitHub. If you can have a go at writing an SQL query which looks for dupes, I'll gladly add it.

**Comment by JonTheNiceGuy** [comment]
I tapped the resource of the AdminAdminPodcast telegram group, and came up with two statements that I need to wrap into something... um, soonish.

***NOTE: I am not a computer scientist, just a hobbyist developer, therefore, I know this is not optimal o(n).***

From the looks of things, you *should* be able to do something like 

```
SELECT benchID, latitude, longitude, soundex(inscription) AS soundex FROM benches
```

You could then (psudocode)

```
COMPARED = []
FOR EACH bench IN results
  FOR EACH benchcheck IN results
    COMPARED.append benchcheck.benchID . "/" . bench.benchID
    IF COMPARED[bench.benchID . "/" . benchcheck.benchID] IS NOT DEFINED
      AND bench.latitude <= (benchcheck.latitude + 0.0005) 
      AND bench.latitude >= (benchcheck.latitude - 0.0005) 
      AND bench.longitude <= (benchcheck.longitude + 0.0005) 
      AND bench.longitude >= (benchcheck.longitude - 0.0005) 
      AND bench.soundex == benchcheck.soundex
    THEN
      PRINT "Possible match: " . bench.benchID . " and " . benchcheck.benchID
  END FOR
END FOR
```

**Comment by edent** [comment]
OK, we've had some more duplicates added! Let's see if this function can find them....

https://openbenches.org/bench/722 and https://openbenches.org/bench/17657
https://openbenches.org/bench/718 and https://openbenches.org/bench/17655
https://openbenches.org/bench/717 and https://openbenches.org/bench/17653 (First one is mistranscribed)
https://openbenches.org/bench/716 and https://openbenches.org/bench/17651
https://openbenches.org/bench/715 and https://openbenches.org/bench/17649
https://openbenches.org/bench/714 and https://openbenches.org/bench/17647
https://openbenches.org/bench/713 and https://openbenches.org/bench/17646

**Comment by edent** [comment]
Hmm... Might be simpler to just run
```
SELECT 
    inscription, 
    COUNT(inscription)
FROM
    benches
WHERE
	published=1
GROUP BY inscription
HAVING COUNT(inscription) > 1
```
Periodically to check for dupes. Reduces the burden on the user. Runs quickly enough that it doesn't need to be geo-bounded.

**Comment by edent** [comment]
A better way, using SOUNDEX.

```
SELECT 
	inscription,
   SOUNDEX(inscription),
   COUNT( SOUNDEX(inscription))
FROM
    benches
WHERE
	published=1
GROUP BY SOUNDEX(inscription)
HAVING COUNT(SOUNDEX(inscription)) > 1
```
There are many genuine dupes. Will look at adding geo-location.
