### ISSUE TITLE
Leaderboard moves edited benches to editor

### ISSUE THREAD

**Issue by Lextuga007** [openbenches/openbenches.org#228]
I corrected one of ukmoose's benches that said Brampton Stoker and should be Bram Stoker and it's now moved to my board. Could the leaderboard be set to count created rather than a last edited field, if that's what is happening?

Thanks

**Comment by jrbray1** [comment]
I like that editing increases your score, as I often forget to login, and then moving the anonymous bench a smidgen gets me the credit. Edits should not reduce anyone's score of course.

**Comment by edent** [comment]
After much thought...

The new version of OpenBenches *ignores* who edits a bench.

If @jrbray1 adds a new bench - then it is theirs no matter how many times @Lextuga007 edits it.

Added images will always belong to whoever uploaded them.

The admin (me!) gets a notification with a user ID of whoever edits a bench, it's also recorded in the database. So any malicious edits can be rolled back and users blocked.

I hope that's satisfactory. And thank you for your patience.

**Comment by jrbray1** [comment]
The easiest solution that stops the system being gamed, not that anyone
really cares. https://openbenches.org/leaderboard says "Most added and
edited benches" which will need changing.
