### ISSUE TITLE
“Benches near me” button on bench page not working

### ISSUE THREAD

**Issue by andylolz** [openbenches/openbenches.org#229]
Works on the homepage, but throws an error on the bench page:

> Uncaught ReferenceError: geoFindMe is not defined
>     at HTMLSpanElement.onclick ((index):164)

Looks like [this geoFindMe script](https://github.com/openbenches/openbenches.org/blob/8c9a3c56f713eb523b246106590e3c2c40c6d578/www/front.php#L67-L98) is missing from the bench page.

![thank you](https://arhklxrfen.cloudimg.io/v7/openbenches.org/image/1d19275bbc3ba4626d41c5bff1c4dc53cac836d7/?w=600)

**Comment by edent** [comment]
Hmm.. #230 works - but because the "bench" page only shows a single bench, it isn't that useful.

As a temporary solution, I'm going to remove the "near me" from the benches page.

**Comment by andylolz** [comment]
Ahh, right yes, I see. Ugh, sorry about that. It was a bit of a hopeful/lazy PR 😞 

I can maybe take a second pass at this.

**Comment by edent** [comment]
Bench page now redirects to the front page "near me" function.
