### ISSUE TITLE
Ingest tweets

### ISSUE THREAD

**Issue by edent** [openbenches/openbenches.org#23]
As a user, I want to Tweet a photo of a bench and have it included.

As suggested by @ekoner

https://twitter.com/ekoner/status/887050145019437057

* Needs geotags
* Link to Twitter photo or get copyright permission?
* Twitter strips EXIF data from photos

**Comment by ekoner** [comment]
I believe [Leeds Art Crawl](http://leeds.artcrawl.club/welcome) uses IFTTT - you need location turned on when you send the tweet.

**Comment by edent** [comment]
Can't be done due to lack of geotagging in most photos.
