### ISSUE TITLE
Incorrect date on photo upload

### ISSUE THREAD

**Issue by boothym** [openbenches/openbenches.org#233]
I uploaded a photo for this bench: https://openbenches.org/bench/18350

The image date was 16th March 2020, however it says "8th Dec 2002"!

**Comment by edent** [comment]
Interesting! The EXIF reports two different dates.

```
  'exif:DateTime' => '2020:03:16 12:50:49',
  'exif:DateTimeDigitized' => '2002:12:08 12:00:00',
  'exif:DateTimeOriginal' => '2020:03:16 12:50:49',
```

See https://openbenches.org/image/e03670a800432471ceb90650371d4d4f06dada3b/exif

Did you upload from your phone directly?

**Comment by boothym** [comment]
No. I copied the photo from my old phone as part of a larger backup (not in 2002 though!), and uploaded it from my laptop yesterday.

**Comment by edent** [comment]
Interesting. The code is at:
https://github.com/openbenches/openbenches.org/blob/313804a98472973b00b6e50220c130f0b572a2f9/www/functions.php#L325

I think I need to reverse that. Start by using the GPSDateStamp, and use the DateTimeDigitized at the end.

Thanks for flagging this up. I'll update the database this weekend, and look at updating the code.
