### ISSUE TITLE
Inscriptions are truncated in the API

### ISSUE THREAD

**Issue by ralight** [openbenches/openbenches.org#236]
For example when viewing bench 26 on the web you get:

https://www.openbenches.org/bench/26
```
Presented to the City of Bath
by the Bath and District
Africa Star Association
May 13th 1987
to commemorate victory
in North Africa 1943
```

But when accessing through the API you get:

https://openbenches.org/api/v1.0/data.json/?bench=26
```
Presented to the City of Bath
by the Bath and District 
Africa Star Association
May 13th 1987 
to commemorate victory 
in …
```

**Comment by edent** [comment]
As per the readme:

* Inscriptions
	* By default, the inscriptions are truncated to 128 characters.
	* To get the full inscriptions, append `&truncated=false`
	* `https://openbenches.org/api/v1.0/data.json/?truncated=false`

So you can use https://openbenches.org/api/v1.0/data.json/?bench=26&truncated=false to get the full inscription.

**Comment by ralight** [comment]
Doh, my apologies for wasting your time.

**Comment by edent** [comment]
No worries. I'm just glad someone is using the API :-)
