### ISSUE TITLE
Show bench icon on default map tiles

### ISSUE THREAD

**Issue by boothym** [openbenches/openbenches.org#238]
Would it be possible to have the default map view show a bench icon, the same as how OSM-carto/Mapnik does? That would make it easier to accurately set the bench location if it is already mapped in OSM.

I realised after I started writing this issue that you can switch between map view and Mapnik in the top right corner - but I still think it would be good to have it for the default map tiles. :)

**Comment by edent** [comment]
What do you mean by Bench icon? I'm not familiar with Mapnik.

At the moment, we use some libraries default pin. But I guess we can replace it. Do you have a link to a preferred graphic?

**Comment by boothym** [comment]
I mean the bench icon used when you zoom in on osm.org - see image.
![bench](https://user-images.githubusercontent.com/16965772/114741138-61d9d400-9d42-11eb-8b62-4101da797a1e.JPG)

If you go here: https://openbenches.org/#55.95122/-3.199937/19 you will see the default map view, by Stadia Maps I think.

If you select the switcher in the top right you can select "Mapnik" to get the map tiles used on osm.org, which shows the benches.

**Comment by edent** [comment]
Ah, those icons come from the tile provider. I can't add them to Stadia. But if you know of another tile provider, we can switch to them instead.

**Comment by boothym** [comment]
Ok, just thought there might be a different theme or custom styles from Stadia that might show them.

As a workaround, are you able to make Mapnik available in the layer switcher when uploading a new bench? Because currently only Map View and Satellite View are available.

**Comment by edent** [comment]
Cheers - I've changed the default add map to Mapnik and set the zoom to max to show the existing bench icons.

Thank you for all your wonderful benches.
