### ISSUE TITLE
Accessibility Issues with IntenseDebate Comment section

### ISSUE THREAD

**Issue by it3986** [openbenches/openbenches.org#245]
When running the Wave Accessibility evaluation tool over a random bench page the main errors showing all relate to the Comments section of the page.

The hint text under each of the input boxes is too low a contrast from the background and is reporting as too small.
The comment text box is also missing a Form label.

![Accessiblity Errors screenshot](https://user-images.githubusercontent.com/4873884/135725546-25ad96d2-31f9-4cfa-a5d4-c98ea2470b8f.JPG)

**Comment by edent** [comment]
Hi, thanks for this. The HTML is generated by IntenseDebate - so I don't think we can change that. But happy to take CSS fixes for the contrast & size issues.

**Comment by it3986** [comment]
Documentation for IntenseDebate suggests local CSS fixes should be possible. I will have a fiddle and see what I can suggest.
https://support.intensedebate.com/css-documentation/
