### ISSUE TITLE
Search function does not explain that no results were found.

### ISSUE THREAD

**Issue by arizonagroovejet** [openbenches/openbenches.org#247]
Steps to recreate:

- Search for something that returns no results, e.g. `supercalifragilisticexpialidocious`

Expected results:
I see some text to the effect that no results were found for the search term.

Actual results:
No information is displayed about the search results. 
![supercalifragilisticexpialidocious](https://user-images.githubusercontent.com/29510692/135755058-50dd82ef-85cf-4854-9838-ac00768fc9d1.jpg)

I'm pretty sure the search function used to say something like "no results found". When I searched earlier for a name to check if a bench was submitted already and got what's shown in the image above I initially thought the search was broken.

**Comment by edent** [comment]
Good spot! Thanks.
