### ISSUE TITLE
Suggestion: Merge bench

### ISSUE THREAD

**Issue by backache** [openbenches/openbenches.org#255]
I have created a duplicate bench, could there be a merge button to bring all the goodness of the two records together?

It'd be a shame if people are just deleting duplicates when a mistake could be turned into an enrichment of an existing record

**Comment by edent** [comment]
Heya, thanks for the suggestion. We do have a merge function, but it is locked behind an admin-only login for now.

At the moment, whenever a bench is uploaded, I get an email saying if it is a possible duplicate. So it isn't much effort for me to merge them once in a while.

Additionally, there are *lots* of things which look like dupes, which aren't. E.g https://openbenches.org/search/?soundex=I561354323 - I didn't want people accidentally merging them.

Finally, if you do spot a bench on the site and want to add more photos to it, there's an edit button at the bottom.

If you can think of a sensible way of letting regular user merge dupes, I'm happy to take suggestions or pull requests.

**Comment by backache** [comment]
Maybe give them a button/form to flag up the dupe that actually behind the scenes just alerts the admins somehow, or perhaps starts the process for an admin just  to okay

btw the dupe I created I was 

Mine (wrong side of the road)
https://openbenches.org/bench/23448/

the one it should be merged into 

https://openbenches.org/bench/15352/

**Comment by edent** [comment]
Cheers - I've merged them.
We have a comment box at the bottom of each page. People usually use that to flag up duplicates, missing data, or incorrect inscriptions.

I'll have a think if there's a better way to do that.
