### ISSUE TITLE
suggestion: fixmystreet intergration

### ISSUE THREAD

**Issue by backache** [openbenches/openbenches.org#257]
I have just started logging benches and so far the ones I have seen are broken or at best need a new coat of varnish.

Could it be possible to have a "report this bench" button that goes to fixmystreet?

For example, I saw someone logged a broken bench in https://www.fixmystreet.com/report/3068394

**Comment by edent** [comment]
It is a possibility. FMS has a lat/long link like https://www.fixmystreet.com/around?js=1&zoom=3&lat=51.234&lon=0.12345

But I'm not quite sure *where* we'd put the link. If it is an existing bench on the site, I'm not sure that people are physically near the bench. If it is on the upload screen, I don't want the user to leave the site to write a report.

**Comment by backache** [comment]
I see what you mean, it'd be nice if they had an API for you to push info into as you already have the stuff they need such as email addresses, coordinates and photos, the only extra information to gather is what's wrong with the bench.

**Comment by edent** [comment]
Yup, the only API is for *viewing* reports - https://www.fixmystreet.com/open311

I'll close this suggestion for now. But feel free to re-open if something changes.

**Comment by backache** [comment]
I have asked in their google-group, let's see what they come back with

https://groups.google.com/a/mysociety.org/g/fixmystreet
