### ISSUE TITLE
Microdata

### ISSUE THREAD

**Issue by backache** [openbenches/openbenches.org#258]
In another thread, microdata was mentioned (to help robots such as search engines and voice assistants understand the data) for each page/entry

What other tags should be added to help make the pages machine-friendly?

For general purposes, the closest thing I could find to a bench is "seat"

https://schema.org/Seat 

```
<meta property="place:location:latitude"  content="52.477772">
<meta property="place:location:longitude" content="-1.898581">
<meta itemprop="latitude"  content="52.477772" />
<meta itemprop="longitude" content="-1.898581" />
```

_Originally posted by @edent in https://github.com/openbenches/openbenches.org/issues/256#issuecomment-1110862341_

**Comment by edent** [comment]
The following microdata is available on every bench page, as can be seen on https://validator.schema.org/
![Screenshot of Schema Markup validator.](https://github.com/openbenches/openbenches.org/assets/837136/91a6a33e-1223-422b-ae31-c4a141ef6d7a)

If you have more suggestions for microdata that we can easily add, please do open a new issue.
