### ISSUE TITLE
Suggestion: Retrieve users location from the browser on the homepage

### ISSUE THREAD

**Issue by backache** [openbenches/openbenches.org#259]
Using something like https://wikishootme.toolforge.org one click on the compass icon on their homepage will request your location fromthe browser and then centre the map on you and  with a maximum zoom, would that an idea with openbenches?

**Comment by edent** [comment]
Hi, we already have a "Benches Near Me" button.
![Screenshot 2022-05-03 at 12-11-51 OpenBenches](https://user-images.githubusercontent.com/837136/166443299-747aedc8-6a72-4bcb-81f6-f870bf05a85c.png)
If you press that, it will request your location, centre the map, and zoom you in.

Is there something else you think it should be doing? Or a way it can be made clearer?

**Comment by backache** [comment]
Could the "benches near me" be zoomed more by default, the current level (10) is 113 miles wide, 15 might be a better level (3.5 miles wide)
