### ISSUE TITLE
"No GPS tags detected" warning when adding image via edit screen

### ISSUE THREAD

**Issue by bennuttall** [openbenches/openbenches.org#260]
I went to edit a few benches today to upload additional images to existing benches, and every time I uploaded the first new image, a JavaScript alert box would give me the following message:

```
Warning! No GPS tags detected in photo.
Please check your camera's settings or add a different photo.
```

![Screenshot from 2022-05-22 23-35-46](https://user-images.githubusercontent.com/1609725/169719051-77426887-3264-4d29-80c4-f68c608872e6.png)

This seems to happen when adding the first new image to an existing bench, but not further new ones within the same edit.

The images I uploaded did in fact have GPS tags, but that's irrelevant as I was adding new images to benches which already had map positions.

**Comment by edent** [comment]
Excellent spot. I think I'll just remove the EXIF check for additional photos. If it causes problems, I'll add it back in.
