### ISSUE TITLE
suggestion: add tagging to the edit screen

### ISSUE THREAD

**Issue by backache** [openbenches/openbenches.org#265]
I thought it would be nice to return to some of my old benches and do some tagging, but that's not an option in edit screen, could it be added?

**Comment by arizonagroovejet** [comment]
I've got a working implementation of this on a local instance of OpenBenches. Current tags are shown between inscription and first photo, like on and using the same dialogue as on the page for adding a bench. 

![Screenshot from 2023-03-05 13-13-05](https://user-images.githubusercontent.com/29510692/222962648-b6902806-0368-478f-9e9b-4b0e3d9f5b37.png)
![Screenshot from 2023-03-05 13-13-29](https://user-images.githubusercontent.com/29510692/222962649-8a07af87-4b8f-4005-83e5-3049295f788d.png)

I need to figure out why `sendmail` on the machine I've got the instance running on seems unhappy and get sending mail to a local inbox to work so I can test changes to tags being included in the email that gets sent when a bench is edited. Also pending finding out what the deal is with #290
