### ISSUE TITLE
suggestion: registering on OpenDOAR

### ISSUE THREAD

**Issue by backache** [openbenches/openbenches.org#269]
Whilst looking at geograph, I noticed its registered on a database of sites on the internet that have collections of data to be shared.

I searched for open benches but did not find it so wondered if it somewhere OB should be registered so as to increase visibility with other opendata type folks?

https://v2.sherpa.ac.uk/opendoar/

**Comment by edent** [comment]
Thanks! I've registered on it. I'll keep this issue open until we get on - or are rejected :-)

**Comment by edent** [comment]
As per discussion with OpenDOAR, I've made the download links prominent. Will see if that's enough.

**Comment by edent** [comment]
https://v2.sherpa.ac.uk/id/repository/10514

Thanks for the tip!
