### ISSUE TITLE
Unable to add video of bench 

### ISSUE THREAD

**Issue by Contributor2230** [openbenches/openbenches.org#272]
# Issue description
I am unable to add videos of benches when creating them. I've only tried this anonymously. 

# Steps I took:
1. https://openbenches.org/add/
2. Click **Upload a geotagged photo of the bench**
3. Select inscription photo
4. Edit inscription text
5. Click **Optional photo of the same bench**
6. Select video
7. In the "This photo is a:" field, select **Video of the bench**
8. Click **Share Bench**

# Expected results:
Video is added and bench entry is created

# Actual results:
1. Upload progress bar animates
2. "Upload complete" text appears briefly
3. Error message: 
"Ooops! Looks like you didn't add a photo. Please reload this page and try a different photo"
<img width="1728" alt="Screen Shot 2022-08-05 at 8 20 24 PM" src="https://user-images.githubusercontent.com/110362694/183225877-0cd52a98-46d1-4384-86ce-c8644783d9b6.png">

# Additional details
This is what the Chrome console shows when I select the video:
```
(index):356 Uncaught TypeError: Failed to execute 'appendChild' on 'Node': parameter 1 is not of type 'Node'.
    at loadImage.maxWidth ((index):356:31)
    at r.onerror (load-image.js:154:28)
loadImage.maxWidth @ (index):356
r.onerror @ load-image.js:154
error (async)
t @ load-image.js:152
m @ load-image.js:194
document.getElementById.onchange @ (index):354
```

No preview of the video is shown before or after uploading.

The videos I tried are MPEG-4 from a Pixel 6 Pro. Sample video info:
Resolution: 3840 × 2160
Video Format: HEVC
Audio Format: AAC, 48000 Hz
Size: 264.2 MB
Duration: 34 seconds

**Comment by edent** [comment]
Thanks for this. I think the issue is that the video is just too large. The maximum upload file size is set to 16MB.

We're really not set up for hosting & serving huge video files.

Could you try compressing the file to under 16MB and let me know if the problem still occurs?
Alternatively, you can host the video on YouTube and put a link to it in the comments?

In the meantime, I'll look at adding a warning so that this sort of error can't happen

**Comment by Contributor2230** [comment]
Thanks for the file size limit info! I compressed the video to get under that limit and was able to upload it.
