### ISSUE TITLE
Suggestion: Dupe spotter

### ISSUE THREAD

**Issue by backache** [openbenches/openbenches.org#276]
I spotted a dupe

https://openbenches.org/bench/25083/
https://openbenches.org/bench/12012/

Could there be a mechanism to spot these given the text and location is roughly identical?

**Comment by backache** [comment]
Maybe some have some text-based reports such as "my benches" or "benches near me" that could flag up dupes and have a button that then alerts an admin?

**Comment by edent** [comment]
Sorry, I wasn't clear enough. I *already* get those reports. The problem is finding the time to deal with them - or preventing them from occurring in the first place.
![Screenshot_20220908-102852](https://user-images.githubusercontent.com/837136/189087486-5df345bc-8574-449e-8e5a-23506f2a1925.jpg)

**Comment by jrbray1** [comment]
When I spot a duplicate I try to explain in the comments, as some people buy 2 benches, or benches move between parks. But I think its an admin role to fix things
