### ISSUE TITLE
suggestion: have "benches near me" zoomed in more

### ISSUE THREAD

**Issue by backache** [openbenches/openbenches.org#277]
"benches near me" starts at a zoom level of 10 which works out at 150km wide

Could "near" perhaps be zoom level 15 which is roughly 4.5km wide

**Comment by edent** [comment]
Sounds good - create a PR and I'll merge it tonight.

**Comment by backache** [comment]
I've not really done that before, I have tried however using version control is all new to me!

**Comment by edent** [comment]
Send a pull request and I'll merge it :-)
