### ISSUE TITLE
Some benches not showing on the map unless you view just that bench.

### ISSUE THREAD

**Issue by arizonagroovejet** [openbenches/openbenches.org#287]
View https://openbenches.org/bench/27699 
Click "Benches near this" button. 
You should now be viewing https://openbenches.org/#52.789371/-1.667/16 and bench 27699 isn't shown.

Same happens if you start by viewing https://openbenches.org/bench/27698 and a few other benches that were tweeted around the same time.

View https://openbenches.org/bench/27691/
Click "Benches new this" button.
Benches 27698 and 27699 should be on the map, but they aren't.

Go to https://openbenches.org/ and zoom in until you find that area and 27698 and 27699 aren't on the map.

**Comment by arizonagroovejet** [comment]
I cannot recreate this today using the examples above nor with some recently added benches in the same area. Possibly it was an issue on my end. Something something cache maybe.

**Comment by edent** [comment]
I've instigated some fairly aggressive caching to lighten the load on the server. The front page data is cached for an hour.

I can't afford to move to a faster host, so that was the best compromise.
