### ISSUE TITLE
Erroneous "l" ?

### ISSUE THREAD

**Issue by arizonagroovejet** [openbenches/openbenches.org#288]
Should the `"l"` element in the `pages` array in `index.php` added in 30aed3803dddc3d92cfc17a9be6643c67d2c56f2  be there?

https://github.com/openbenches/openbenches.org/blob/bb0ea062bd5b348ad43b249cd7a13111396f2476/www/index.php#L16

There is no file called `l.php`. https://openbenches.org/l/ is an empty page and requesting `/l/` from a local instance causes this error:
```
[Thu Feb 23 20:15:27 2023] PHP Warning:  include(l.php): Failed to open stream: No such file or directory in /var/www/html/index.php on line 19
[Thu Feb 23 20:15:27 2023] PHP Warning:  include(): Failed opening 'l.php' for inclusion (include_path='.:/usr/share/pear:/usr/share/php') in /var/www/html/index.php on line 19
```

**Comment by edent** [comment]
Good spot! I think it was left over from trying to do something clever with locations.

Feel free to send a PR to remove it.
