### ISSUE TITLE
The page moves when the inscription comes back

### ISSUE THREAD

**Issue by bennuttall** [openbenches/openbenches.org#296]
It's a small thing but the fact the inscription box has more height than the informational text it replaces means that all the elements below it shift down when the auto inscription comes back from the API.

What I often find it that I'm about to drag & drop my second image into the file upload area and as I drop it, the inscription text has just arrived and I've accidentally dropped the image onto the page, outside the file drop area, meaning I lose the page and have to start the process again.

Before:

![Screenshot from 2023-03-19 23-30-30](https://user-images.githubusercontent.com/1609725/226216759-fe4dbcb5-b8d4-4e4b-a447-a393ac8343a0.png)

After:

![Screenshot from 2023-03-19 23-30-40](https://user-images.githubusercontent.com/1609725/226216774-b61af7a1-fb0a-444e-888d-9d639fa64d8b.png)

If the "Automatic text detection in progress" message was in a box the same height as the inscription textarea, nothing on the page would need to move, and this wouldn't be a problem.

**Comment by edent** [comment]
I think the easiest solution is going to be to keep the text area visible from the start, but set it to `disabled` while the auto detection is running.
