### ISSUE TITLE
Users can't change the "type" of images on the edit page

### ISSUE THREAD

**Issue by bennuttall** [openbenches/openbenches.org#297]
Sometimes I realise I've selected the wrong image type (or left it at the auto-selected one) and I have no way of correcting it. This is especially bad if the system thinks it's a 360° image:

![Screenshot from 2023-03-19 23-10-04](https://user-images.githubusercontent.com/1609725/226216897-bbb8607c-40fd-4767-a272-a71e96f90409.png)

The bench in question: https://openbenches.org/bench/27855

**Comment by edent** [comment]
Thanks. I've manually fixed that one. Will give some thought to the editing page.
