### ISSUE TITLE
Uploaded images are badly scaled on the edit page

### ISSUE THREAD

**Issue by bennuttall** [openbenches/openbenches.org#298]
If you upload an image on the "new bench" page, it looks ok:

![Screenshot from 2023-03-19 23-08-14](https://user-images.githubusercontent.com/1609725/226217136-32d7fb1e-3c07-4ec5-a11d-1e7052b64de5.png)

However, if you upload an image on the "edit bench" page, it looks oddly scaled:

![Screenshot from 2023-03-19 23-10-21](https://user-images.githubusercontent.com/1609725/226217140-62414a9b-77d7-436a-9710-efef0c8c484f.png)

When I say "uploaded" I really just mean selected in the browser, rather than uploaded to the server. Both images are after selection but before upload.

**Comment by edent** [comment]
Good spot! In `add.php` the width is 800. No idea why I set it as 400 in `edit.php`.  Will update.
