### ISSUE TITLE
Tags aren't showing up, or not saved, or something

### ISSUE THREAD

**Issue by arizonagroovejet** [openbenches/openbenches.org#304]
https://openbenches.org/bench/28208 - I specified four tags when adding this bench: dog, park, wood, metal. None of them are show up on the bench page. The call to `save_tags()` is no longer commented out, the saving of tags works in my local instance, so the only idea I have about this is that the call to `save_tags()` is still commented out in the code on the server. :man_shrugging:

**Comment by edent** [comment]
Hmmm, something reverted on the server. Fixed now (I hope!)
