### ISSUE TITLE
Some images have no media type

### ISSUE THREAD

**Issue by edent** [openbenches/openbenches.org#307]
1,427 images have no media type - this leads to broken alt text and poor quality data.

**Comment by edent** [comment]
Listed at https://openbenches.org/admin/no-mediatypes - click to edit!

**Comment by edent** [comment]
Down to a mere 756 benches remaining. Good work everyone!

**Comment by arizonagroovejet** [comment]
The list is empty . ;)

**Comment by edent** [comment]
Woo! 1000 points to you @arizonagroovejet :-)
