### ISSUE TITLE
Unable to upload when logged-in with Github

### ISSUE THREAD

**Issue by pikesley** [openbenches/openbenches.org#308]
# How to reproduce

* Go to https://openbenches.org/
* Click on `Add bench`
* Click on `Sign in`, `Continue with Github`
* Complete the Github auth steps
* Get returned to https://openbenches.org/add/
* Which is just this 
![Screenshot from 2023-05-01 11-56-09](https://user-images.githubusercontent.com/885973/235443205-9c7502b8-5c35-4f74-a20f-1ca5267c72fd.png)
* Clicking the `Add bench` button does nothing

# Clients tried

I got the same result on:
* Android Chrome
* Android Firefox
* Linux Chrome

**Comment by edent** [comment]
This is very strange. I can see that some people are still signing in via GitHub - https://openbenches.org/bench/28592 - and I'm able to sign in.

Could you please try visiting https://openbenches.org/logout and see if that helps?

I'm in the process of finding a new social sign on service, so this is a good data point.

**Comment by pikesley** [comment]
> This is very strange. I can see that some people are still signing in via GitHub - https://openbenches.org/bench/28592 - and I'm able to sign in.
> 
> Could you please try visiting https://openbenches.org/logout and see if that helps?
> 
> I'm in the process of finding a new social sign on service, so this is a good data point.

This didn't make any difference, and I've since tried in it on my Mac with Chrome, Firefox and Safari and I get the same every time

**Comment by DamianMehers** [comment]
Same thing using Edge in Parallels on my Mac (GitHub authentication). Will try an actual Windows computer.

**Comment by edent** [comment]
The bad news is... I have no idea what's causing this. Only happens on Safari - which I have replicated.
The good new is... I have fixed this! The site rewrite should be live this weekend. I'll update this when done.

**Comment by edent** [comment]
I think this is now fixed. Can you try going to https://openbenches.org/logout and then https://openbenches.org/add/logged_in

**Comment by DamianMehers** [comment]
I've been looking at all the benches I pass waiting for one with an inscription.  Captured this one on my morning run, GitHub login worked perfectly https://openbenches.org/bench/28724

Thanks!

**Comment by edent** [comment]
Thanks. I've now fixed the editing as well.
