### ISSUE TITLE
Unreliable upload service

### ISSUE THREAD

**Issue by jrbray1** [openbenches/openbenches.org#309]
Over the last few weeks I've frequently found the uploading mechanism to be unreliable, timing out, or giving the 503 service unavailable. Only half the uploads work. Are there better times of day, or should I just let my backlog of benches accumulate until something improves?

**Comment by edent** [comment]
It's a fair point. At the moment I'm limited by the resources I have. My host regularly sends me messages like this:
![Screenshot saying Resource limits hit.](https://user-images.githubusercontent.com/837136/236544688-7b282f92-3433-43e6-a37b-bdb9b7677e06.png)

I'm rewriting the code to be more memory and CPU efficient. I'm hoping to have in ready in a few weeks.

The current host is a 2GB, 2 CPU, 50 entry process machine with unlimited disk space.  We're at 255GB of photo - so really need the storage. Hosting costs are currently £120 per year.

I'm open to suggestions for faster hosts - or donations so I can increase the resources of the existing one.

**Comment by jrbray1** [comment]
For speed I tend to have 4 tabs open, 3 uploading in turn, one for searching, so I'm hammering the server. I'll hold off my backlog until you've finished the upgrade, and perhaps be gentler with you. £120 sounds a fair price. I use Dreamhost, which can struggle with my wikis on their shared servers, and cost much the same.

**Comment by edent** [comment]
I've update the code to be more efficient - which should reduce errors (famous last words). However, I'd appreciate you only uploading one bench at a time until I can raise funds for something faster.

**Comment by jrbray1** [comment]
Will do. Just had a go and got the following screenshot

**Comment by edent** [comment]
I don't think image attachments work when replying to GitHub by email.

**Comment by jrbray1** [comment]
Hopefully I've sent it directly to a valid email address for you

**Comment by jrbray1** [comment]
![2](https://github.com/openbenches/openbenches.org/assets/25801685/46fcc112-03b0-494d-945d-1ef896029ebe)
or attaching something here
