### ISSUE TITLE
Opengraph title doubly encodes entities 

### ISSUE THREAD

**Issue by Krinkle** [openbenches/openbenches.org#311]
The HTML entities are displayed to end users in social media previews and in instant messengers when sharing links such as https://openbenches.org/bench/28650

example:
https://botsin.space/@openbenches/110328685829097306

> `Vera &amp; Joe Brownbill
 27.03.41 - 18.12.20
 17.07.40 02.01.21
 60 years married, [..]`

**Comment by edent** [comment]
So, I *think* this is either fixed or there's a bug with Mastodon.

For example - https://openbenches.org/bench/28559 - renders an OpenGraph preview correctly on Twitter and Facebook.

It's possible that Mastodon is caching the OG preview from before the rewrite.

**Comment by edent** [comment]
Fixed. See https://botsin.space/@openbenches/110362456193339742
