### ISSUE TITLE
Login button on the homepage

### ISSUE THREAD

**Issue by backache** [openbenches/openbenches.org#329]
If you are not logged in, there is no button to do so

The current workaround is to add bench and click the one on the resulting page  (https://openbenches.org/add)

**Comment by edent** [comment]
I can do, but I guess I don't understand *why* you want to log in on the home page?

Login only changed the add & edit pages. It doesn't change anything else.

**Comment by backache** [comment]
I wanted to go my userpage so as too see if there was somewhere to add my mastodon address and to see the benches I have added so I may tag them

**Comment by backache** [comment]
Just tried to login and it errored


[Image]




Sent from my mobile, sorry for any typo's
________________________________
