### ISSUE TITLE
Some addresses have HTML entities in them

### ISSUE THREAD

**Issue by edent** [openbenches/openbenches.org#333]
For example https://openbenches.org/bench/14061

`Carriage &amp; Wagon Workshop, Station Road, Tenterden, United Kingdom`

**Comment by computamike** [comment]
Have been able to - sort of - replicate the issue by editing the sample database, and updating an `&` in record 143 to be `&amp;` - which renders the same as the affected bench.
![image](https://github.com/openbenches/openbenches.org/assets/464876/55a6ad99-8bfc-4853-a5f8-ff84b8106492)

This address data is returned from a reverse GeoCoding - I believe that this service that performed the reverse geocoding, has inserted these HTML chars, and these are being saved into the database.

I think someone would need to confirm the theory - I tried dumping the data for the bench - but there's no address data in there  - [https://openbenches.org/api/bench/14061](https://openbenches.org/api/bench/14061).

Hi @edent - I've had a look at this issue using my new fangled docker install.

Here's what I've figured out so far:  

- Looking in the code- there are multiple reverse geocode API's in use - so this might be related to a specific API - however there is nothing in the data to confirm which API this data (and potentially more) has been provided by.  A clean method could be added after the API call to clean up any data that has been returned from an API provider that potentially contains html encoded data - You could use [`html_entity_decode`](https://www.php.net/manual/en/function.html-entity-decode).
  - This will prevent the problem getting worse - but does nothing to fix the data that is in the DB. 
  - I'd also be tempted to strip any tags in that API response also.
- Then the next step might be to clean up the data that is in the DB 
  - This could be done by performing a query that scans for address fields that contain chars, maybe using the RLIKE function? and update them (MariaDB doesn't have a html decoding function from what I can see.  This might be a good way to determine the scale of the problem.
  - An alternative might be some form of cleanse script that could be run that checks the address field, fixing any broken addresses, and updating the record.

It might be tempting to leave the data and add a `html_entity_decode` call from the controller - And that might be a quick temporary solution while someone works on the longer term solutions,  but I'd be worried that this might affect search results.  I think that it would be generally safer to fix the data in the database.

**Comment by edent** [comment]
I've manually fixed the data. I suspect one of the reverse geocoders was a bit dodgy.
