### ISSUE TITLE
 Something is broken. Please let us know what you were doing when this error occurred.

### ISSUE THREAD

**Issue by jrbray1** [openbenches/openbenches.org#334]
I was uploading a complicated bench with 3 plaques, so only one long view, and got this. A simple upload 5 min later worked.

An Error Occurred
"500 - Internal Server Error"

Something is broken. Please let us know what you were doing when this error occurred.

I will fix it as soon as possible. Sorry for any inconvenience caused.

Details
#0 /home/openbenc/public_html/vendor/symfony/http-kernel/HttpKernel.php(163): ()
#1 /home/openbenc/public_html/vendor/symfony/http-kernel/HttpKernel.php(74): Symfony\Component\HttpKernel\HttpKernel->handleRaw()
#2 /home/openbenc/public_html/vendor/symfony/http-kernel/Kernel.php(184): Symfony\Component\HttpKernel\HttpKernel->handle()
#3 /home/openbenc/public_html/vendor/symfony/runtime/Runner/Symfony/HttpKernelRunner.php(35): Symfony\Component\HttpKernel\Kernel->handle()
#4 /home/openbenc/public_html/vendor/autoload_runtime.php(29): Symfony\Component\Runtime\Runner\Symfony\HttpKernelRunner->run()
#5 /home/openbenc/public_html/public/index.php(5): require_once('/home/openbenc/...')
#6 {main}

**Comment by edent** [comment]
Thanks for the report. It is hard tracking these transient errors. They're a lot less common than before, but seem to occur when the server is under heavy load.

Did you manage to upload your photos in the end? I can check the DB to see if they made it ok.

**Comment by jrbray1** [comment]
I tried again tonight, and 25 benches from Wales with no trouble at all. Passed 3000 now.
