### ISSUE TITLE
Cannot set bench location; Leaflet is a gray box

### ISSUE THREAD

**Issue by jcoscia** [openbenches/openbenches.org#335]
When attempting to add a bench, after I upload the image, I am unable to mark where the bench is, with Leaflet. The Leaflet box is a gray box, and I cannot pan or zoom in/out. Screenshot attached.

I tried using Chromium 113.0.5672.63 and Firefox 112.0.1, and was able to reproduce the issue with both. Adblock and other extensions/features that can interfere were switched off.

![openbenches org_add](https://github.com/openbenches/openbenches.org/assets/22737219/fafeec76-3525-4ed4-a1ec-224dc52d9e63)

**Comment by edent** [comment]
Hmmm. Something has gone very wrong there. You're also missing the emoji on the tags, share button, optional photo, and made with <3. 
Can I ask which OS you're using?

**Comment by jcoscia** [comment]
I am using Fedora 36 (from within [Qubes](https://www.qubes-os.org/)).

I also tried using Vanadium (Chromium fork) from my Android phone, as well as Tor Browser, and the same issue occurs. The emojis do render on those, though.

**Comment by edent** [comment]
This is very strange. I've tried Chromium and Firefox on Ubuntu, and on Android, and they work.

Are you able to view the maps on the homescreen? We use a different mapping provider on the add screen - and I wonder if you have something on your network blocking it.

**Comment by edent** [comment]
Closed due to lack of information. Please re-open if you have further details.
