### ISSUE TITLE
Add bench

### ISSUE THREAD

**Issue by BubbleRLA** [openbenches/openbenches.org#336]
I'm trying to figure out how to add a bench.  Help please.

**Comment by arizonagroovejet** [comment]
Have you tried clicking the "Add bench" button? :wink:  If so, perhaps if you provided more information about exactly what part of the process you're having trouble with someone might be able to help.

![Screenshot from 2023-07-08 16-05-41](https://github.com/openbenches/openbenches.org/assets/29510692/dd883712-ab4e-4642-85b0-a58628010431)

**Comment by BubbleRLA** [comment]
Yes, I clicked on add bench.  It won't let me upload a photo.

**Comment by arizonagroovejet** [comment]
Can you tell us

- Exactly what are you doing to try and upload a photo.
- What happens as a result of you doing that.
- The full  and exact wording of any error messages which are displayed.
- Which web browser you are using. 
- Are you trying to do it on a phone or a tablet or a computer?
-  What operating system does the phone/tablet/computer run?

I realise that's a lot of questions, but the key to someone helping you is knowing as much as possible about what is happening to result in you saying you can't upload a photo. It may even help if you can provide the date and time of when you have tried to upload a photo and found you can't, as someone with access to the server logs might be able to find an explanation there.

**Comment by edent** [comment]
Closed for lack of information. Please re-open if you have any more details.
