### ISSUE TITLE
Bench 185 issues

### ISSUE THREAD

**Issue by arizonagroovejet** [openbenches/openbenches.org#340]
In addition to not having a media type for the photo (as mention in #307) the image for bench 185 doesn't load with viewed at https://openbenches.org/bench/185 or https://openbenches.org/edit/185 In both cases I get this URL for the image https://images.weserv.nl/?url=openbenches.org/image/2a49f2947efa3073268333252fc4aa6c9933053e/&w=600&q=60&output=webp&il   and it returns some JSON
`{"status":"error","code":404,"message":"The requested URL returned error: 301"}`
and HTTP status code 404.

Also I think it might be a dupe of https://openbenches.org/bench/186 or, perhaps one could argue that I inadvertently made it a dupe. I went to edit 185 and got an error so tried the next in the list at https://openbenches.org/admin/no-mediatypes, which was 186, noticed that the inscription text was missing some of what's in the photo so added it. Then when I went back to try 185 again I realised the text I'd added to 186 is the current text for 185. 186 is obviously one bench with two plaques but I think someone submitted as 185 with the text from one plaque then again as 186 with the text from the second plaque.

**Comment by edent** [comment]
Looks like the CDN was having a glitch. The image is working now.

I *think* @jnicho02 added a separate entry for each separate plaque. Which was a sensible thing to do back in the early days when we didn't really know the shape of the project.

I've now merged them.
