### ISSUE TITLE
Some benches have images which are more than one media type.

### ISSUE THREAD

**Issue by arizonagroovejet** [openbenches/openbenches.org#341]
While going through the list of benches with no media type (#307), I discovered some benches which have only one image and most of it appears to be "view from the bench" but also part of it is "close-up of the inscription". I set them to "view from bench" as that's what they mostly are. But perhaps someone can think of reasons why it would be better for them to be classed as "close-up of the inscription".

https://openbenches.org/bench/288
https://openbenches.org/bench/286
https://openbenches.org/bench/285
https://openbenches.org/bench/284
https://openbenches.org/bench/283
https://openbenches.org/bench/282
https://openbenches.org/bench/281

**Comment by edent** [comment]
Thanks for going through all of those - very impressive!

I think for the ones where it is uncertain either leave them blank or use your best judgement. It's always going to be a little fuzzy.
