### ISSUE TITLE
Account Limit Exceeded on map

### ISSUE THREAD

**Issue by jrbray1** [openbenches/openbenches.org#342]
Looking at the top page I get a "account limit exceeded" graphic rather than the map
![2](https://github.com/openbenches/openbenches.org/assets/25801685/f251bbe5-b0be-4cd8-b9bd-3d71b7413512)

**Comment by edent** [comment]
We've had a rather busy month! Give me a few moments and I'll get it fixed.

**Comment by edent** [comment]
In the meantime, you can click the tiles icon in the top right to switch to a different map provider.

**Comment by edent** [comment]
Stuck in a temporary fix. Will make it more permanent at the next billing cycle.
