### ISSUE TITLE
365 is not a bench.

### ISSUE THREAD

**Issue by arizonagroovejet** [openbenches/openbenches.org#344]
https://openbenches.org/bench/365   That's not a bench, it's a stone in the ground.

**Comment by edent** [comment]
Good spot, I'll remove it shortly. BTW - editing might be a bit unstable while I work on a load issue. You may see multiple markers when editing. Should be fixed shortly. Thanks for all your help with this!

**Comment by arizonagroovejet** [comment]
I was just now opening the edit page of random benches to see if they all have multiple markers and thinking, I'm sure there weren't multiple markers earlier today! (Sometimes Formula 1 races aren't very exciting and one can easily do something else at the same time without missing anything. ;) )

**Comment by edent** [comment]
Fixed! Ta.
