### ISSUE TITLE
Edit page doesn't always visually link image types to images

### ISSUE THREAD

**Issue by arizonagroovejet** [openbenches/openbenches.org#352]
E.g. https://openbenches.org/edit/391 in Firefox full screen on a 1920px wide monitor looks like this;
![Screenshot from 2023-07-28 15-55-07](https://github.com/openbenches/openbenches.org/assets/29510692/69f0e1ca-dee4-47d7-b16a-a4a988118ee0)

**Comment by edent** [comment]
Good spot, thanks!
