### ISSUE TITLE
Less precision for addresses

### ISSUE THREAD

**Issue by edent** [openbenches/openbenches.org#354]
Addresses are hard. But perhaps we only need Country, Major Locality, Minor Locality.

Otherwise we end up with this!
![Screenshot of an address of Dog Water Bin.](https://github.com/openbenches/openbenches.org/assets/837136/af03f3aa-612c-4328-886d-4b8b472c8a71)

**Comment by arizonagroovejet** [comment]
Also, as I think I've commented before, the specificness of a lot of addresses shown for benches makes them nonsensical. E.g. https://openbenches.org/bench/19622  It's not on Fledburgh Drive, yet alone at 163-177 Fledburgh Drive.  You can see the  Brass Rubbing Centre on Southern Lane from https://openbenches.org/bench/1766, but it's on the other side of a river.

Tangentially, I had the thought the other day that reducing specificity of addresses might make it possible to do the reverse geoencoding offline and remove dependency on external services which might incur costs. I got as far as thinking one of the cities files from http://download.geonames.org/export/dump/ might facilitate that but haven't been able to identify a suitable PHP library.  Perhaps it doesn't have to be done with PHP. Perhaps it doesn't have to be done as part of the process of adding a bench and could be delegated to a separate batch process which runs in the small hours of the UK timezone when load on the site is likely to be very low to none (given a large majority of benches which get added are in the UK.)

**Comment by edent** [comment]
Thankfully we now have enough sponsorship to pay for Stadia Maps. That means much more consistent and fine grained geocoding.
Over the next few weeks I'll be redoing all the addresses and the geocoding functions.
