### ISSUE TITLE
Potential Error when running DB scripts - Maybe... Could someone confirm?

### ISSUE THREAD

**Issue by computamike** [openbenches/openbenches.org#356]
When executing the DB scripts (as part of the docker build), the following errors can be seen in the output logs : 

```
2023-08-01 22:29:27 ERROR 1366 (22007) at line 1734: Incorrect string value: '\xF0\x9F\xA6\x8B I...' for column `openbenc_benches`.`benches`.`inscription` at row 178
2023-08-01 22:29:28 ERROR 1366 (22007) at line 1719: Incorrect string value: '\xF0\x9F\x9A\xB4\x0D\x0A...' for column `openbenc_benches`.`benches_history`.`address` at row 145
2023-08-01 22:29:38 ERROR 1452 (23000) at line 117: Cannot add or update a child row: a foreign key constraint fails (`openbenc_benches`.`#sql-alter-64-10`, CONSTRAINT `benches_history_ibfk_1` FOREIGN KEY (`benchID`) REFERENCES `benches` (`benchID`))
```

I looked into these issues, and it seems to be related to inserting emoji chars into the database - it's possible that the Foreign Key issue is related to one of these records not being present (will research this later)

## Background
For the Docker build, I am using a MariaDB container - which ships with the MariaDB client.  The only change I had to make to get the Database script to execute (as provided in the [CONTRIBUTING](https://github.com/openbenches/openbenches.org/blob/be6d31fe6c402770023c5abdd20b5c2683563d6a/CONTRIBUTING.md) documentation) was to change `mysql` to `mariadb`

By default, both mySQL and mariaDB have Latin as their default character set.  I think that when I was connecting to the DB using the Client CLI, that it was connecting using Latin character set, and that caused a problem inserting those characters.

I found that if I added `--default-character-set=utf8mb4 ` to the code to execute the script, that it fixes the issue, and the data imports correctly, so it might also be that if you have mysql client installed and have set up the `default-character-set` value in a config file, that the script works fine without setting the character set in the CLI.

## Steps to reproduce the issue
These instructions are based on using the mariadb cli - I understand that it is pretty similar to the MySQL cli.  

If you are a user who has never had a problem running the script from the [CONTRIBUTING ](https://github.com/openbenches/openbenches.org/blob/be6d31fe6c402770023c5abdd20b5c2683563d6a/CONTRIBUTING.md) doc, then you might already have `default-character-set=utf8mb4 ` set in one of your config files.

Running with `--no-defaults` means that this setting is ignored - and the error condition is confirmed.
Running with `--no-defaults` and `--default-character-set=utf8mb4` shows that forcing the default (hopefully) fixes the issue.

- Dump out the client defaults `mariadb --print-defaults`
  - note if there is an option there for `default-character-set`
- Run the following command from the `database` folder 
  - `mariadb --no-defaults -u openbenches -pbadpassword -D openbenc_benches < openbenc_benches_table_benches_history.sql`
  - replace the credentials with whatever is relevant for your environment
  - Hopefully, the following error should be shown:
  - ``ERROR 1366 (22007) at line 1719: Incorrect string value: '\xF0\x9F\x9A\xB4\x0D\x0A...' for column `openbenc_benches`.`benches_history`.`address` at row 145``
- Now run a slightly modified version of the same command, and hopefully it should complete with no issues.
  - `mariadb --no-defaults -u openbenches -pbadpassword -D openbenc_benches --default-character-set=utf8mb4 < openbenc_benches_table_benches_history.sql`

If this works, then this might highlights a potential issue when running the scripts - that your MySQL Client needs to have a default character set of  `utf8mb4`.   

One solution might be to update the [CONTRIBUTING ](https://github.com/openbenches/openbenches.org/blob/be6d31fe6c402770023c5abdd20b5c2683563d6a/CONTRIBUTING.md)document to include the information that the database scripts need a default character set of  `utf8mb4`.  This might be an issue if you are developing on multiple projects at the same time, in which case a better solution might be to update the script to include the default character set.

**Comment by pwaring** [comment]
I used MySQL when creating Docker containers, as that matches what is used by the website. I wasn't sure what version was used but the mysql:5.7 image works.

**Comment by edent** [comment]
Sorry for the confusion, the guide was written by multiple people and may not be consistent.

On the OpenBenches server we use `utf8mb4_unicode_ci`

**Comment by computamike** [comment]
thanks @edent  - So what you are referring to there is collation - I was referring to the character set- which I believe is `utf8mb4` based on the Database dump scripts 

https://github.com/openbenches/openbenches.org/blob/37de2dcd656e33af43a8e0e9b3990397db61704a/database/openbenc_benches_database.sql#L24.

Can you confirm whether the server is running with mySQL, or MariaDB?  So far I have been testing against MariaDB - but happy to switch to MySQL if that is what the server is running on.

**Comment by edent** [comment]
Apparently my server is 10.6.14-MariaDB-cll-lve-log
