### ISSUE TITLE
broken link on blog

### ISSUE THREAD

**Issue by alifeee** [openbenches/openbenches.org#360]
on the page <https://www.openbenches.org/blog/about/>, this link is a placeholder link

![image](https://github.com/openbenches/openbenches.org/assets/13833017/064e9802-cb4f-4a87-8214-e4ff79198d6c)

I would fix it but I don't believe the blog content is on this repo

:)

**Comment by edent** [comment]
Good spot! Now fixed.
Thanks :-)
