### ISSUE TITLE
Handle bad EXIF location data better

### ISSUE THREAD

**Issue by RedAuburn** [openbenches/openbenches.org#361]
uploading a bad exif results in an uncaught error, and a grey map:

![image](https://github.com/openbenches/openbenches.org/assets/26939824/1dfddbe2-b23f-4ccd-bc75-7cef2e360e7e)

with this image:
![2024-04-10-10-35-34-076](https://github.com/openbenches/openbenches.org/assets/26939824/e6f9ef9d-6a94-404c-bfd2-2efa4affdf25)

in console: 
```
Uncaught Error: Invalid LatLng object: (NaN, NaN)
    v LatLng.js:32
    w LatLng.js:123
    setView Map.js:181
    exifdata logged_in:420
    i load-image-meta.js:166
    onload load-image.js:64
    d load-image.js:63
    i load-image-meta.js:100
    c load-image-meta.js:183
    <anonymous> logged_in:336
    EventHandlerNonNull* logged_in:315
```

of course, bad exif shouldn't be created in the first place, but it'd be good to handle it.
maybe a toast warning that the exif data isn't parseable etc.
(issue for bad exif creation is here: https://gitlab.com/LineageOS/issues/android/-/issues/6987)

**Comment by edent** [comment]
Oooh, interesting. Yes, the code should alert on NaN. I'll see if I can fix it.

Thanks for all the great benches!

**Comment by RedAuburn** [comment]
Woah that was quick, thank you! 😊
