### ISSUE TITLE
New tag suggestion: 'Composite'

### ISSUE THREAD

**Issue by jackmcconnell** [openbenches/openbenches.org#362]
I've noticed a lot of newer benches are made of a composite material, mostly wooden and recylced plastic, for longevity and easier cleaning. 
I'd like to suggest this as an additional tag, probably next to 'wooden' when adding a new bench. 

I'm not familiar with twig so wasn't sure how to add this as a PR.

**Comment by edent** [comment]
Good idea. The tags are drawn from the database, so there's nothing to edit in the Twig. I've made that update.

Thanks for all the lovely photos.
