### ISSUE TITLE
Check for duplicate before upload (& pls fix duplicate)

### ISSUE THREAD

**Issue by RedAuburn** [openbenches/openbenches.org#363]
Accidentally uploaded a duplicate:
https://openbenches.org/bench/31906
is duplicate of
https://openbenches.org/bench/22134

Also, using the API to get all benches in a ~200m radius, comparing the inscriptions to the current upload attempt, then warning the user that the bench is likely a duplicate would be a handy feature :)

It would have fixed this duplicate upload where the inscriptions were identical, and the position was less than a metre apart

**Comment by edent** [comment]
Thanks for the suggestion. I receive an email every time there's a new bench uploaded. That email also tells me if it is a likely duplicate based on the SOUNDEX of the inscription.  If it is a legitimate duplicate, I can merge them.

So if you visit https://openbenches.org/bench/31906 you'll be redirected to the original - which now also has your excellent photos on it. Incidentally, someone else duplicated that bench in 2023 as well. It is popular!

I did experiment with automatic duplication detection but there are a couple of difficulties.

1. It places more work on the uploader. On a small screen it might be difficult to detect if something is a dupe.
2. It is more complex code. I don't want to worry about a bunch of different states.
3. There are a *lot* of benches with identical inscriptions which are near to each other.  I think the false positive rate is likely to be so high that it is annoying for users.
4. Some benches do get moved a considerable distance. Especially in parks. By having a manual review I can look closely at the photos and check whether it really is the same bench, just moved to the other side of the river.

So, for now, I'm going to leave it. I'm happy to do the manual deduplication on the rare occasions when it happens.

**Comment by RedAuburn** [comment]
fair enough, thanks :)
