### ISSUE TITLE
API filter for "most recent X benches"

### ISSUE THREAD

**Issue by alifeee** [openbenches/openbenches.org#364]
I'd like to fetch the most recent 1/5/10 benches.

Currently, I can use the RSS feed for this on <https://openbenches.org/feed>, as it is limited to the most recent 100.

It might be nice for the geoJSON API to offer this, for example as

`https://openbenches.org/api/benches?limit=5` or `https://openbenches.org/api/benches?latest=5`

One could just call `https://openbenches.org/api/benches` and grab the final 1/5/10 items in the geoJSON object, but there is a lot of frivolous data transfer asking for ALL benches when you only need the bottom 1/5/10.

**Comment by edent** [comment]
A good idea!

The "nearest" API calls use `limit` - however that's a subtly different use-case.

`/api/benches` returns the benches in the order they were added. So `limit=5` should return only the first 5 benches, which isn't what you wanted.  So I think `latest=5` would probably work best.

**Comment by alifeee** [comment]
that's wonderful :)
