### ISSUE TITLE
500 errors and duplicates

### ISSUE THREAD

**Issue by jrbray1** [openbenches/openbenches.org#365]
After a 500 error and "Upload faied", there are now 3 identical benches.

https://openbenches.org/search?search=FASLEY+TYLER

**Comment by jrbray1** [comment]
Name was wrong, and fixed so search for https://openbenches.org/search?search=PASLEY

**Comment by edent** [comment]
Thanks for the info. I've merged and deduplicated to https://openbenches.org/bench/32121

Brilliant pictures! Sorry about the 500 errors.
