### ISSUE TITLE
Krakow benches, stalling

### ISSUE THREAD

**Issue by jrbray1** [openbenches/openbenches.org#366]
Lots of benches round Krakow, with QR codes to find out more about the authors featured. Rather than have a clumsy set of information, I think its best to just have the name, as with https://openbenches.org/bench/32355

The site is stalling badly on the "redirecting you" message, even after another window shows its been added correctly.

**Comment by edent** [comment]
Thanks @jrbray1 - I agree, just the name is fine.
Sorry about the slowness. It takes some time for the service to post to Mastodon & send an email. I'll see if there's any way I can get that to work in the background.

**Comment by edent** [comment]
From examining the code, it appears to be the autoposting to Mastodon which is the cause of the slowness. I'll see if I can make it asynchronous.

**Comment by edent** [comment]
Looks like it is fixed. Added a bunch recently without issue.
