### ISSUE TITLE
Sign in with Wordpress errors out

### ISSUE THREAD

**Issue by paulwakeford** [openbenches/openbenches.org#368]
Invalid request, please go back and try again.
Error Code: invalid_request
Error Message: Invalid "scope". See https://developer.wordpress.com/docs/oauth2/#token-scope.

I don't need it, just noticed it.

**Comment by edent** [comment]
Thanks. I've raised a ticket with Auth0. Really wish we could move away from them!

**Comment by edent** [comment]
Hopefully being tracked by Auth0 https://github.com/auth0/wordpress/issues/906#issuecomment-2187268976

**Comment by edent** [comment]
I've attended an Okta developer day and have escalated it there. Fingers crossed!

**Comment by edent** [comment]
Auth0 have *finally* fixed this. I've tested it and was able to login with WordPress. If you notice it not working again, please let me know.
