### ISSUE TITLE
API could return 301 or redirected data

### ISSUE THREAD

**Issue by alifeee** [openbenches/openbenches.org#369]
Some benches are duplicates. For example, id 33030 is a duplicate.

<https://openbenches.org/bench/33030> redirects to <https://openbenches.org/bench/18924>

This is evident by the headers (notably HTTP 302)

```bash
$ curl -i https://openbenches.org/bench/33030
HTTP/2 302
cache-control: no-cache, no-store, must-revalidate, max-age=0
location: /bench/18924
content-type: text/html; charset=utf-8
date: Mon, 24 Jun 2024 11:58:51 GMT
server: LiteSpeed
vary: User-Agent,User-Agent
x-robots-tag: noai
alt-svc: h3=":443"; ma=2592000, h3-29=":443"; ma=2592000, h3-Q050=":443"; ma=2592000, h3-Q046=":443"; ma=2592000, h3-Q043=":443"; ma=2592000, quic=":443"; ma=2592000; v="43,46"

<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8" />
        <meta http-equiv="refresh" content="0;url='/bench/18924'" />

        <title>Redirecting to /bench/18924</title>
    </head>
    <body>
        Redirecting to <a href="/bench/18924">/bench/18924</a>.
    </body>
</html>
```

The API doesn't contain any indication if 33030 is a duplicate, only returning empty JSON data

```bash
$ curl -i https://openbenches.org/api/bench/33030
HTTP/2 200
cache-control: no-cache, private
content-type: application/json
date: Mon, 24 Jun 2024 11:58:56 GMT
server: LiteSpeed
vary: User-Agent,User-Agent
x-robots-tag: noai
alt-svc: h3=":443"; ma=2592000, h3-29=":443"; ma=2592000, h3-Q050=":443"; ma=2592000, h3-Q046=":443"; ma=2592000, h3-Q043=":443"; ma=2592000, quic=":443"; ma=2592000; v="43,46"

{}
```

The API could return a 301 redirect, or something in the return data to suggest that the bench is redirected.

A 301 would be useful in my case, but I'm not sure how common this is with an API, and something in the `body` of the request might be preferable.

I'm happy to attempt this change if pointed to the bits of code which deal with redirects for normal pages, and the API code file.

Thanks!

**Comment by edent** [comment]
That's an excellent suggestion, thanks!

The API code is in https://github.com/openbenches/openbenches.org/blob/master/www/src/Controller/ApiController.php

The database will return `0` in the `published` column.

In the table `merged_benches` run 
```
SELECT `mergedID` FROM `merged_benches` WHERE `benchID` = 33030 `
```

That should return `18924` and the API query can be re-run.

**Comment by alifeee** [comment]
wonderful :)
