### ISSUE TITLE
Missing submit button 

### ISSUE THREAD

**Issue by metbril** [openbenches/openbenches.org#372]
I'm trying to add a bench with my iPhone. Both anonymously and logged in I don't see a submit button. Am I missing something?

**Comment by metbril** [comment]
It was a HEIC issue

**Comment by edent** [comment]
Thanks for letting me know. I'll see if there's some way I can filter out HEIC so it doesn't show.

**Comment by metbril** [comment]
FYI, I was able to select the heic from my file browser, but it do anything. And didn't show a submit button. When I did a closer look, I noticed that it wasn't a jpeg. After fixing that everything went smoothly. 

My suggestion would be to show a red notice when someone selects an unsupported filetype for uploading.
