### ISSUE TITLE
Unable to upload some images

### ISSUE THREAD

**Issue by kvaradhan3** [openbenches/openbenches.org#373]
Hi folks:

I am baffled by the response on the `Add Bench` workflow and need some help/clarity.

- THe first pic was to `Upload a geotagged photograph of the bench` which I did. 
- Automatic Text-detection worked wonders, and then
- the map below updated to the right location, and then allowed me precise fix the point, if I choose.

When I then went to share the bench, I got this message:

```
No location metadata found in image.
[Please reload this page and try a different photo](https://openbenches.org/add)
```
and the upload/share is stalled.

FWIW:  I added https://openbenches.org/bench/34744 earlier using identical equipment (a crappy pixel6, geotagged the precise location using the exiftool) and that went through without a hitch.   Had to add the text by hand there, no text autodetection.

Any help?

THanks,

Kannan

Picture Details:
```
❯ exiftool PXL_20240907_153434728.MP.jpg | grep -i gps     ⚡▮▮▮▮▮▮▮▮▮▮ 9:48:30
GPS Version ID                  : 2.2.0.0
GPS Latitude Ref                : North
GPS Longitude Ref               : West
GPS Img Direction Ref           : Magnetic North
GPS Img Direction               : 283
GPS Latitude                    : 37 deg 10' 51.58" N
GPS Longitude                   : 121 deg 51' 15.42" W
GPS Position                    : 37 deg 10' 51.58" N, 121 deg 51' 15.42" W
```

**Comment by kvaradhan3** [comment]
![PXL_20240907_153442706 MP](https://github.com/user-attachments/assets/ace472c3-f11e-44cc-acb5-9c4f3be5341f)

For reference, that is one of the three photos of this bench I was trying to upload...

**Comment by edent** [comment]
Hi @kvaradhan3 thanks for the lovely photos you've uploaded.

I'll admit, I'm a bit baffled by this as well! I just tried uploading the photo - and it worked https://openbenches.org/bench/34747 

I'm happy to assign it to your account on the leader-board if you like?

Could you please let me know what sort of device you were using when the error occurred (phone, laptop, etc) and the browser & version.

All I can think of is that the JS to detect the location somehow didn't load properly.

**Comment by kvaradhan3** [comment]
> Hi @kvaradhan3 thanks for the lovely photos you've uploaded.
> 
> I'll admit, I'm a bit baffled by this as well! I just tried uploading the photo - and it worked https://openbenches.org/bench/34747
> 
> I'm happy to assign it to your account on the leader-board if you like?
> 
> Could you please let me know what sort of device you were using when the error occurred (phone, laptop, etc) and the browser & version.
> 
> All I can think of is that the JS to detect the location somehow didn't load properly.

I think you may be right.   I was using orion, from kagi:

```
❯ brew info orion                                        ⚡▮▮▮▮▮▮▮▮▮▮ 10:34:00
==> orion: 0.99,128.2.1 (auto_updates)
https://browser.kagi.com/
Installed
/opt/homebrew/Caskroom/orion/0.99,128.2.1 (621.8MB)
==> Name
Orion Browser
==> Description
WebKit based web browser
==> Artifacts
Orion.app (App)
```

I generally dont use the corp browser for personal stuff, but when I switched to chrome, it uploaded here:  https://openbenches.org/bench/34748

Thanks for the quick response...

more soon,

Thanks for the interesting web site, really cool

**Comment by kvaradhan3** [comment]
Sorry, I missed the context of what you were suggesting @edent and went ahead and pushed up separately.   Hope that is ok....
