### ISSUE TITLE
De-spherication for 360° images in twitter:image and og:image meta tags

### ISSUE THREAD

**Issue by alexdutton** [openbenches/openbenches.org#48]
No idea how to do this, but would it be a good idea to transform spherical images for displaying in media thumbnails?

The derived image could be overlaid with some sort of logo to show that there's actually a 360° image to be seen.

(Other questions about choosing a direction, or whether to e.g. tile four images from compass points, are left open…)

**Comment by edent** [comment]
Brilliant idea! I've also 你idea how to implement it. Can you try and find a PHP image manipulation script that could help?

**Comment by edent** [comment]
I can't find a sensible way to do this :-( 

Very few panoramic images are uploaded, so closing for now.
