### ISSUE TITLE
Some images upside down / rotated

### ISSUE THREAD

**Issue by edent** [openbenches/openbenches.org#64]
This image displays normally in the browser https://openbenches.org/image/a04a681d2ed94cb52ddfc3dc5d62a4209bcacbad/600

On the website it is upside down https://openbenches.org/bench/1039

`image-orientation: from-image;` is Firefox only https://developer.mozilla.org/en-US/docs/Web/CSS/image-orientation

**Comment by edent** [comment]
Nope! Now iPhones see them upside down!!

**Comment by edent** [comment]
Can set the EXIF, but some services still rotate them.
https://twitter.com/openbenches/status/896458382168780802

**Comment by ajhard** [comment]
This is odd...when I try and upload from my iPhone (iOS 10) images are often rotated incorrectly, but this never occurs on my iPad (iOS 11 beta).

**Comment by edent** [comment]
There's something odd with iPhones. Hopefully all future images will use EXIF to correctly orient themselves.
Closing for now, but please re-open if you spot any upside down.

**Comment by edent** [comment]
Some browsers are displaying some images upside down.
https://openbenches.org/bench/14458

Right way up - https://openbenches.org/image/02f331fe6a203019893d53037941a859fb4c4128/
Upside down - https://arhklxrfen.cloudimg.io/v7/openbenches.org/image/02f331fe6a203019893d53037941a859fb4c4128/?w=600

See thread at https://twitter.com/edent/status/1197892091399028737

**Comment by edent** [comment]
Looks like a webp issue https://twitter.com/AlecEast/status/1197920603111612416

**Comment by edent** [comment]
Fixed by CloudImg
